import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRemainingQuantityAndPurchaseId1784438049276 implements MigrationInterface {
    name = 'AddRemainingQuantityAndPurchaseId1784438049276'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_role"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_role"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_user_permissions_user"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_user_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_product_images_product"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_category"`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" DROP CONSTRAINT "FK_customer_addresses_customer"`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" DROP CONSTRAINT "FK_customer_tag_map_customer"`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" DROP CONSTRAINT "FK_customer_tag_map_tag"`);
        await queryRunner.query(`ALTER TABLE "order_notes" DROP CONSTRAINT "FK_order_notes_order"`);
        await queryRunner.query(`ALTER TABLE "order_returns" DROP CONSTRAINT "FK_order_returns_order"`);
        await queryRunner.query(`ALTER TABLE "order_returns" DROP CONSTRAINT "FK_order_returns_order_item"`);
        await queryRunner.query(`ALTER TABLE "order_returns" DROP CONSTRAINT "FK_order_returns_customer"`);
        await queryRunner.query(`ALTER TABLE "order_delivery" DROP CONSTRAINT "FK_order_delivery_order"`);
        await queryRunner.query(`ALTER TABLE "order_delivery" DROP CONSTRAINT "FK_order_delivery_partner"`);
        await queryRunner.query(`ALTER TABLE "delivery_charge_rules" DROP CONSTRAINT "FK_delivery_charge_rules_partner"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_customer"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_address"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_store"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_coupon"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_applied_rule"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_product_batches_variant"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_product_batches_store"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_order"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_variant"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_batch"`);
        await queryRunner.query(`ALTER TABLE "stock_logs" DROP CONSTRAINT "FK_stock_logs_variant"`);
        await queryRunner.query(`ALTER TABLE "stock_logs" DROP CONSTRAINT "FK_stock_logs_store"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_product_variants_product"`);
        await queryRunner.query(`ALTER TABLE "store_inventory" DROP CONSTRAINT "FK_store_inventory_store"`);
        await queryRunner.query(`ALTER TABLE "store_inventory" DROP CONSTRAINT "FK_store_inventory_variant"`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" DROP CONSTRAINT "FK_product_material_usage_material"`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" DROP CONSTRAINT "FK_product_material_usage_variant"`);
        await queryRunner.query(`ALTER TABLE "material_purchases" DROP CONSTRAINT "FK_material_purchases_material"`);
        await queryRunner.query(`ALTER TABLE "material_purchases" DROP CONSTRAINT "FK_material_purchases_supplier"`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" DROP CONSTRAINT "FK_product_cost_summary_product"`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" DROP CONSTRAINT "FK_product_cost_summary_batch"`);
        await queryRunner.query(`ALTER TABLE "hero_media" DROP CONSTRAINT "FK_hero_media_section"`);
        await queryRunner.query(`ALTER TABLE "store_inventory" DROP CONSTRAINT "UQ_store_inventory_store_variant"`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" DROP CONSTRAINT "UQ_product_cost_summary_product_batch"`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" ADD "purchase_id" bigint`);
        await queryRunner.query(`ALTER TABLE "material_purchases" ADD "quantity_remaining" numeric(10,3) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`UPDATE "material_purchases" SET "quantity_remaining" = "quantity"`);
        await queryRunner.query(`CREATE INDEX "idx_role_perm_permission_id" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_role_perm_role_id" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_perm_user_allowed" ON "user_permissions" ("user_id", "allowed") `);
        await queryRunner.query(`CREATE INDEX "idx_user_perm_permission_id" ON "user_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_perm_user_id" ON "user_permissions" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "store_inventory" ADD CONSTRAINT "UQ_60ade8c3b6fd5afd16ed220ebe7" UNIQUE ("store_id", "variant_id")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_3495bd31f1862d02931e8e8d2e8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_8145f5fadacd311693c15e41f10" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" ADD CONSTRAINT "FK_6be4e1a698f5c3f2c2e4c75c186" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" ADD CONSTRAINT "FK_e20e457eda9c5674db1233d0b6b" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" ADD CONSTRAINT "FK_300b29990dbeb66b4da0f46b767" FOREIGN KEY ("tag_id") REFERENCES "customer_tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_notes" ADD CONSTRAINT "FK_2c241096df74dd0d8e1fc16ed63" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_returns" ADD CONSTRAINT "FK_bcd8e1a275860e70f3a876d718f" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_returns" ADD CONSTRAINT "FK_cce6be7edde74393312b16d0a13" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_returns" ADD CONSTRAINT "FK_7e2768334852c43650b250ec5da" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_delivery" ADD CONSTRAINT "FK_41b0ff2fd57678b803b6c202267" FOREIGN KEY ("delivery_partner_id") REFERENCES "delivery_partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_delivery" ADD CONSTRAINT "FK_b6c4b4e2b369a6af48a9ddabca5" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_charge_rules" ADD CONSTRAINT "FK_f7ffc1c7f97d439607d8173fd04" FOREIGN KEY ("delivery_partner_id") REFERENCES "delivery_partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_d39c53244703b8534307adcd073" FOREIGN KEY ("address_id") REFERENCES "customer_addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_6284f0f60e4cb96c12ff96f0f15" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_d10e2c59883abdfe75ccacc2c5f" FOREIGN KEY ("applied_rule_id") REFERENCES "delivery_charge_rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_9e874589807ffcc252fb3b06fc7" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_d81021d7d38f88f85c7c62630ab" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_db2d0ea722e16e0fe8ab3bce111" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9b8893e08d3779cd4c540c866c8" FOREIGN KEY ("batch_id") REFERENCES "product_batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_logs" ADD CONSTRAINT "FK_1a6e0ffeca41d4870227efce53a" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_inventory" ADD CONSTRAINT "FK_5e68b7ed564877449f5d37e7da9" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_inventory" ADD CONSTRAINT "FK_7e33028a75b8fdfc433ac5b794f" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" ADD CONSTRAINT "FK_4a4e55bf73faa126eea83c52c07" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" ADD CONSTRAINT "FK_0f8bb216ec16da829a84e37ec8b" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" ADD CONSTRAINT "FK_f2e07251326110ea2714777154e" FOREIGN KEY ("purchase_id") REFERENCES "material_purchases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_purchases" ADD CONSTRAINT "FK_8f711f075f39a7cd5030c68bbd6" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_purchases" ADD CONSTRAINT "FK_5ee94c4348f4db5095bf5b077e1" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" ADD CONSTRAINT "FK_d35f15893e5e29f8d2725d5ddc5" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" ADD CONSTRAINT "FK_b1a0007bcaea43b76f958cb56f4" FOREIGN KEY ("batch_id") REFERENCES "product_batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hero_media" ADD CONSTRAINT "FK_1d2b3e55943ad2b82d05802e29b" FOREIGN KEY ("hero_section_id") REFERENCES "hero_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "hero_media" DROP CONSTRAINT "FK_1d2b3e55943ad2b82d05802e29b"`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" DROP CONSTRAINT "FK_b1a0007bcaea43b76f958cb56f4"`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" DROP CONSTRAINT "FK_d35f15893e5e29f8d2725d5ddc5"`);
        await queryRunner.query(`ALTER TABLE "material_purchases" DROP CONSTRAINT "FK_5ee94c4348f4db5095bf5b077e1"`);
        await queryRunner.query(`ALTER TABLE "material_purchases" DROP CONSTRAINT "FK_8f711f075f39a7cd5030c68bbd6"`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" DROP CONSTRAINT "FK_f2e07251326110ea2714777154e"`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" DROP CONSTRAINT "FK_0f8bb216ec16da829a84e37ec8b"`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" DROP CONSTRAINT "FK_4a4e55bf73faa126eea83c52c07"`);
        await queryRunner.query(`ALTER TABLE "store_inventory" DROP CONSTRAINT "FK_7e33028a75b8fdfc433ac5b794f"`);
        await queryRunner.query(`ALTER TABLE "store_inventory" DROP CONSTRAINT "FK_5e68b7ed564877449f5d37e7da9"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "stock_logs" DROP CONSTRAINT "FK_1a6e0ffeca41d4870227efce53a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9b8893e08d3779cd4c540c866c8"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_db2d0ea722e16e0fe8ab3bce111"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_d81021d7d38f88f85c7c62630ab"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_9e874589807ffcc252fb3b06fc7"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_d10e2c59883abdfe75ccacc2c5f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_6284f0f60e4cb96c12ff96f0f15"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_d39c53244703b8534307adcd073"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "delivery_charge_rules" DROP CONSTRAINT "FK_f7ffc1c7f97d439607d8173fd04"`);
        await queryRunner.query(`ALTER TABLE "order_delivery" DROP CONSTRAINT "FK_b6c4b4e2b369a6af48a9ddabca5"`);
        await queryRunner.query(`ALTER TABLE "order_delivery" DROP CONSTRAINT "FK_41b0ff2fd57678b803b6c202267"`);
        await queryRunner.query(`ALTER TABLE "order_returns" DROP CONSTRAINT "FK_7e2768334852c43650b250ec5da"`);
        await queryRunner.query(`ALTER TABLE "order_returns" DROP CONSTRAINT "FK_cce6be7edde74393312b16d0a13"`);
        await queryRunner.query(`ALTER TABLE "order_returns" DROP CONSTRAINT "FK_bcd8e1a275860e70f3a876d718f"`);
        await queryRunner.query(`ALTER TABLE "order_notes" DROP CONSTRAINT "FK_2c241096df74dd0d8e1fc16ed63"`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" DROP CONSTRAINT "FK_300b29990dbeb66b4da0f46b767"`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" DROP CONSTRAINT "FK_e20e457eda9c5674db1233d0b6b"`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" DROP CONSTRAINT "FK_6be4e1a698f5c3f2c2e4c75c186"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_8145f5fadacd311693c15e41f10"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_3495bd31f1862d02931e8e8d2e8"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "store_inventory" DROP CONSTRAINT "UQ_60ade8c3b6fd5afd16ed220ebe7"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_perm_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_perm_permission_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_perm_user_allowed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_role_perm_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_role_perm_permission_id"`);
        await queryRunner.query(`ALTER TABLE "material_purchases" DROP COLUMN "quantity_remaining"`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" DROP COLUMN "purchase_id"`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" ADD CONSTRAINT "UQ_product_cost_summary_product_batch" UNIQUE ("product_id", "batch_id")`);
        await queryRunner.query(`ALTER TABLE "store_inventory" ADD CONSTRAINT "UQ_store_inventory_store_variant" UNIQUE ("variant_id", "store_id")`);
        await queryRunner.query(`ALTER TABLE "hero_media" ADD CONSTRAINT "FK_hero_media_section" FOREIGN KEY ("hero_section_id") REFERENCES "hero_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" ADD CONSTRAINT "FK_product_cost_summary_batch" FOREIGN KEY ("batch_id") REFERENCES "product_batches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_cost_summary" ADD CONSTRAINT "FK_product_cost_summary_product" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_purchases" ADD CONSTRAINT "FK_material_purchases_supplier" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_purchases" ADD CONSTRAINT "FK_material_purchases_material" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" ADD CONSTRAINT "FK_product_material_usage_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_material_usage" ADD CONSTRAINT "FK_product_material_usage_material" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_inventory" ADD CONSTRAINT "FK_store_inventory_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_inventory" ADD CONSTRAINT "FK_store_inventory_store" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_product_variants_product" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_logs" ADD CONSTRAINT "FK_stock_logs_store" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_logs" ADD CONSTRAINT "FK_stock_logs_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_batch" FOREIGN KEY ("batch_id") REFERENCES "product_batches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_product_batches_store" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_product_batches_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_applied_rule" FOREIGN KEY ("applied_rule_id") REFERENCES "delivery_charge_rules"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_coupon" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_store" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_address" FOREIGN KEY ("address_id") REFERENCES "customer_addresses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_charge_rules" ADD CONSTRAINT "FK_delivery_charge_rules_partner" FOREIGN KEY ("delivery_partner_id") REFERENCES "delivery_partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_delivery" ADD CONSTRAINT "FK_order_delivery_partner" FOREIGN KEY ("delivery_partner_id") REFERENCES "delivery_partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_delivery" ADD CONSTRAINT "FK_order_delivery_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_returns" ADD CONSTRAINT "FK_order_returns_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_returns" ADD CONSTRAINT "FK_order_returns_order_item" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_returns" ADD CONSTRAINT "FK_order_returns_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_notes" ADD CONSTRAINT "FK_order_notes_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" ADD CONSTRAINT "FK_customer_tag_map_tag" FOREIGN KEY ("tag_id") REFERENCES "customer_tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_tag_map" ADD CONSTRAINT "FK_customer_tag_map_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" ADD CONSTRAINT "FK_customer_addresses_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_category" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_product_images_product" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_user_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_user_permissions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
